<H1> PLEASE GO THROUGH READ-ME FIRST <H1>

In [358]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import itertools

In [359]:
df = pd.read_csv('creditcard.csv')

In [360]:
df['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [361]:
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [362]:
fraud_transactions = df[df['Class']==1]
legit_transactions = df[df['Class']==0]

In [363]:
legit_transactions_undersampled = legit_transactions.sample(len(fraud_transactions))

In [364]:
data = pd.concat([fraud_transactions,legit_transactions_undersampled])
data.reset_index(drop=True, inplace=True)

In [365]:
data['Class'].value_counts()

1    492
0    492
Name: Class, dtype: int64

In [136]:
features = data.drop(columns=['Class'])
true_labels = data['Class']

In [137]:
features = np.array(features)
true_labels = np.array(true_labels)

In [138]:
s_scalar = StandardScaler()
features = s_scalar.fit_transform(features)

In [139]:
X_train, X_test, Y_train, Y_test = train_test_split(features, true_labels, test_size=0.2)

In [372]:
from sklearn import linear_model
from sklearn.metrics import classification_report, confusion_matrix

regr = linear_model.LogisticRegression(solver='lbfgs', max_iter=10000)
regr.fit(X_train, Y_train)
yhat = regr.predict(X_test)
report = classification_report(Y_test,yhat)
print(report)

              precision    recall  f1-score   support

           0       0.90      0.99      0.94       102
           1       0.99      0.88      0.93        95

    accuracy                           0.94       197
   macro avg       0.95      0.94      0.94       197
weighted avg       0.94      0.94      0.94       197



In [373]:
conf_matrix = confusion_matrix(Y_test,yhat)
print(conf_matrix)

[[101   1]
 [ 11  84]]


In [374]:
from sklearn.tree import DecisionTreeClassifier

In [375]:
decisionTree = DecisionTreeClassifier(criterion="entropy", max_depth = 4)
decisionTree.fit(X_train,Y_train)
yhat = decisionTree.predict(X_test)
report = classification_report(Y_test,yhat)
print(report)

              precision    recall  f1-score   support

           0       0.90      0.98      0.94       102
           1       0.98      0.88      0.93        95

    accuracy                           0.93       197
   macro avg       0.94      0.93      0.93       197
weighted avg       0.94      0.93      0.93       197



In [376]:
conf_matrix = confusion_matrix(Y_test,yhat)
print(conf_matrix)

[[100   2]
 [ 11  84]]


In [379]:
decisionTree = DecisionTreeClassifier(criterion="entropy", max_depth = 5)
decisionTree.fit(X_train,Y_train)
yhat = decisionTree.predict(X_test)
report = classification_report(Y_test,yhat)
print(report)

              precision    recall  f1-score   support

           0       0.92      0.95      0.94       102
           1       0.95      0.92      0.93        95

    accuracy                           0.93       197
   macro avg       0.93      0.93      0.93       197
weighted avg       0.93      0.93      0.93       197



In [380]:
conf_matrix = confusion_matrix(Y_test,yhat)
print(conf_matrix)

[[97  5]
 [ 8 87]]


In [381]:
decisionTree = DecisionTreeClassifier(criterion="entropy", max_depth = 6)
decisionTree.fit(X_train,Y_train)
yhat = decisionTree.predict(X_test)
report = classification_report(Y_test,yhat)
print(report)

              precision    recall  f1-score   support

           0       0.90      0.96      0.93       102
           1       0.95      0.88      0.92        95

    accuracy                           0.92       197
   macro avg       0.93      0.92      0.92       197
weighted avg       0.93      0.92      0.92       197



In [382]:
conf_matrix = confusion_matrix(Y_test,yhat)
print(conf_matrix)

[[98  4]
 [11 84]]


In [387]:
decisionTree = DecisionTreeClassifier(criterion="entropy", max_depth = 7)
decisionTree.fit(X_train,Y_train)
yhat = decisionTree.predict(X_test)
report = classification_report(Y_test,yhat)
print(report)

              precision    recall  f1-score   support

           0       0.91      0.96      0.93       102
           1       0.96      0.89      0.92        95

    accuracy                           0.93       197
   macro avg       0.93      0.93      0.93       197
weighted avg       0.93      0.93      0.93       197



In [388]:
conf_matrix = confusion_matrix(Y_test,yhat)
print(conf_matrix)

[[98  4]
 [10 85]]


In [391]:
decisionTree = DecisionTreeClassifier(criterion="entropy", max_depth = 8)
decisionTree.fit(X_train,Y_train)
yhat = decisionTree.predict(X_test)
report = classification_report(Y_test,yhat)
print(report)

              precision    recall  f1-score   support

           0       0.90      0.93      0.92       102
           1       0.92      0.89      0.91        95

    accuracy                           0.91       197
   macro avg       0.91      0.91      0.91       197
weighted avg       0.91      0.91      0.91       197



In [392]:
conf_matrix = confusion_matrix(Y_test,yhat)
print(conf_matrix)

[[95  7]
 [10 85]]


In [393]:
decisionTree = DecisionTreeClassifier(criterion="entropy", max_depth = 9)
decisionTree.fit(X_train,Y_train)
yhat = decisionTree.predict(X_test)
report = classification_report(Y_test,yhat)
print(report)

              precision    recall  f1-score   support

           0       0.91      0.95      0.93       102
           1       0.94      0.89      0.92        95

    accuracy                           0.92       197
   macro avg       0.93      0.92      0.92       197
weighted avg       0.92      0.92      0.92       197



In [394]:
conf_matrix = confusion_matrix(Y_test,yhat)
print(conf_matrix)

[[97  5]
 [10 85]]


In [395]:
decisionTree = DecisionTreeClassifier(criterion="entropy", max_depth = 10)
decisionTree.fit(X_train,Y_train)
yhat = decisionTree.predict(X_test)
report = classification_report(Y_test,yhat)
print(report)

              precision    recall  f1-score   support

           0       0.90      0.96      0.93       102
           1       0.95      0.88      0.92        95

    accuracy                           0.92       197
   macro avg       0.93      0.92      0.92       197
weighted avg       0.93      0.92      0.92       197



In [396]:
conf_matrix = confusion_matrix(Y_test,yhat)
print(conf_matrix)

[[98  4]
 [11 84]]


Decision Tree with max depth=5, provides best F-1 Score, along with reasonable precision and recall for fraud class [which is our goal]
Only 8 incorrect decision in case when actual Labels are false

In [401]:
from sklearn import svm
clf = svm.SVC(kernel='rbf')
clf.fit(X_train, Y_train) 
yhat = clf.predict(X_test)
report = classification_report(Y_test,yhat)
print(report)

              precision    recall  f1-score   support

           0       0.89      0.99      0.94       102
           1       0.99      0.86      0.92        95

    accuracy                           0.93       197
   macro avg       0.94      0.93      0.93       197
weighted avg       0.94      0.93      0.93       197



/opt/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [402]:
conf_matrix = confusion_matrix(Y_test,yhat)
print(conf_matrix)

[[101   1]
 [ 13  82]]


In [403]:
clf = svm.SVC(kernel='poly', degree=2)
clf.fit(X_train, Y_train) 
yhat = clf.predict(X_test)
report = classification_report(Y_test,yhat)
print(report)

              precision    recall  f1-score   support

           0       0.70      0.98      0.82       102
           1       0.96      0.56      0.71        95

    accuracy                           0.78       197
   macro avg       0.83      0.77      0.76       197
weighted avg       0.83      0.78      0.77       197



/opt/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [404]:
conf_matrix = confusion_matrix(Y_test,yhat)
print(conf_matrix)

[[100   2]
 [ 42  53]]


In [405]:
clf = svm.SVC(kernel='poly', degree=3)
clf.fit(X_train, Y_train) 
yhat = clf.predict(X_test)
report = classification_report(Y_test,yhat)
print(report)

              precision    recall  f1-score   support

           0       0.82      1.00      0.90       102
           1       1.00      0.76      0.86        95

    accuracy                           0.88       197
   macro avg       0.91      0.88      0.88       197
weighted avg       0.90      0.88      0.88       197



/opt/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [406]:
conf_matrix = confusion_matrix(Y_test,yhat)
print(conf_matrix)

[[102   0]
 [ 23  72]]


In [407]:
clf = svm.SVC(kernel='linear')
clf.fit(X_train, Y_train) 
yhat = clf.predict(X_test)
report = classification_report(Y_test,yhat)
print(report)

              precision    recall  f1-score   support

           0       0.90      1.00      0.95       102
           1       1.00      0.88      0.94        95

    accuracy                           0.94       197
   macro avg       0.95      0.94      0.94       197
weighted avg       0.95      0.94      0.94       197



In [408]:
conf_matrix = confusion_matrix(Y_test,yhat)
print(conf_matrix)

[[102   0]
 [ 11  84]]


In [409]:
from sklearn.neighbors import KNeighborsClassifier

In [414]:
k = 2
neigh = KNeighborsClassifier(n_neighbors = k)
neigh.fit(X_train,Y_train)
yhat = neigh.predict(X_test)
report = classification_report(Y_test,yhat)
print(report)

              precision    recall  f1-score   support

           0       0.87      0.98      0.92       102
           1       0.98      0.84      0.90        95

    accuracy                           0.91       197
   macro avg       0.92      0.91      0.91       197
weighted avg       0.92      0.91      0.91       197



In [415]:
conf_matrix = confusion_matrix(Y_test,yhat)
print(conf_matrix)

[[100   2]
 [ 15  80]]


In [416]:
k = 3
neigh = KNeighborsClassifier(n_neighbors = k)
neigh.fit(X_train,Y_train)
yhat = neigh.predict(X_test)
report = classification_report(Y_test,yhat)
print(report)

              precision    recall  f1-score   support

           0       0.87      0.98      0.92       102
           1       0.98      0.84      0.90        95

    accuracy                           0.91       197
   macro avg       0.92      0.91      0.91       197
weighted avg       0.92      0.91      0.91       197



In [417]:
conf_matrix = confusion_matrix(Y_test,yhat)
print(conf_matrix)

[[100   2]
 [ 15  80]]


In [418]:
k = 4
neigh = KNeighborsClassifier(n_neighbors = k)
neigh.fit(X_train,Y_train)
yhat = neigh.predict(X_test)
report = classification_report(Y_test,yhat)
print(report)

              precision    recall  f1-score   support

           0       0.86      0.99      0.92       102
           1       0.99      0.82      0.90        95

    accuracy                           0.91       197
   macro avg       0.92      0.91      0.91       197
weighted avg       0.92      0.91      0.91       197



In [419]:
conf_matrix = confusion_matrix(Y_test,yhat)
print(conf_matrix)

[[101   1]
 [ 17  78]]


In [420]:
k = 5
neigh = KNeighborsClassifier(n_neighbors = k)
neigh.fit(X_train,Y_train)
yhat = neigh.predict(X_test)
report = classification_report(Y_test,yhat)
print(report)

              precision    recall  f1-score   support

           0       0.87      0.98      0.92       102
           1       0.98      0.84      0.90        95

    accuracy                           0.91       197
   macro avg       0.92      0.91      0.91       197
weighted avg       0.92      0.91      0.91       197



In [421]:
conf_matrix = confusion_matrix(Y_test,yhat)
print(conf_matrix)

[[100   2]
 [ 15  80]]


In [422]:
k = 6
neigh = KNeighborsClassifier(n_neighbors = k)
neigh.fit(X_train,Y_train)
yhat = neigh.predict(X_test)
report = classification_report(Y_test,yhat)
print(report)

              precision    recall  f1-score   support

           0       0.86      0.99      0.92       102
           1       0.99      0.83      0.90        95

    accuracy                           0.91       197
   macro avg       0.93      0.91      0.91       197
weighted avg       0.92      0.91      0.91       197



In [423]:
conf_matrix = confusion_matrix(Y_test,yhat)
print(conf_matrix)

[[101   1]
 [ 16  79]]


In [424]:
k = 7
neigh = KNeighborsClassifier(n_neighbors = k)
neigh.fit(X_train,Y_train)
yhat = neigh.predict(X_test)
report = classification_report(Y_test,yhat)
print(report)

              precision    recall  f1-score   support

           0       0.87      0.98      0.92       102
           1       0.98      0.84      0.90        95

    accuracy                           0.91       197
   macro avg       0.92      0.91      0.91       197
weighted avg       0.92      0.91      0.91       197



In [425]:
conf_matrix = confusion_matrix(Y_test,yhat)
print(conf_matrix)

[[100   2]
 [ 15  80]]


In [435]:
from sklearn.cluster import KMeans 
clusterNum = 2
k_means = KMeans(init = "k-means++", n_clusters = clusterNum, n_init = 12)
k_means.fit(X_train)
yhat = neigh.predict(X_test)
report = classification_report(Y_test,yhat)
print(report)

              precision    recall  f1-score   support

           0       0.87      0.98      0.92       102
           1       0.98      0.84      0.90        95

    accuracy                           0.91       197
   macro avg       0.92      0.91      0.91       197
weighted avg       0.92      0.91      0.91       197



In [436]:
conf_matrix = confusion_matrix(Y_test,yhat)
print(conf_matrix)

[[100   2]
 [ 15  80]]


In [453]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=100, criterion='gini', random_state = 0)
model.fit(X_train, Y_train)
yhat = model.predict(X_test)
report = classification_report(Y_test,yhat)
print(report)

              precision    recall  f1-score   support

           0       0.90      1.00      0.95       102
           1       1.00      0.88      0.94        95

    accuracy                           0.94       197
   macro avg       0.95      0.94      0.94       197
weighted avg       0.95      0.94      0.94       197



In [454]:
conf_matrix = confusion_matrix(Y_test, yhat)
print(conf_matrix)

[[102   0]
 [ 11  84]]
